require("./start");
require("./follow");
require("./price");
require("./currentStatus");
require("./subscriptions");
require("./cancel");
require("./cancelAll");
require("./listCryptocurrency");
require("./help");
