require("./start");
require("./takip");
require("./fiyat");
require("./iptal");
require("./tumiptal");
require("./sondurum");
require("./aboneliklerim");
require("./bilgi");
require("../callbackQuery/index");
